# Generated by Django 4.2.6 on 2023-10-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
