# Generated by Django 4.2.7 on 2023-12-31 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 31, 12, 52, 25, 935272, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
