# Generated by Django 4.2.6 on 2023-11-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_verified",),
    ]
