# Generated by Django 4.2.7 on 2023-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_onetimepassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="code",
            field=models.CharField(default=["0", "6", "9", "5"], max_length=4),
        ),
    ]
