# Generated by Django 4.2.7 on 2023-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_onetimepassword_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="one_time_password",
            field=models.CharField(default="0000", max_length=4),
        ),
        migrations.DeleteModel(name="OneTimePassword",),
    ]
