# Generated by Django 4.2.7 on 2023-11-10 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_one_time_password_delete_onetimepassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_expire",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Otp Expire"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_send",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
