# Generated by Django 4.2.7 on 2023-11-10 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_otp_expire_user_otp_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_expire",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 10, 20, 28, 53, 419424, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Otp Expire",
            ),
        ),
    ]
