# Generated by Django 4.2.7 on 2023-11-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_expire_otp"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="expire_otp",),
        migrations.AddField(
            model_name="user",
            name="one_time_password_send",
            field=models.BooleanField(default=False),
        ),
    ]
