# Generated by Django 4.2.7 on 2024-01-02 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_user_uuid_alter_business_company_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 22, 16, 10, 201583, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
