# Generated by Django 4.2.7 on 2023-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_user_expire_otp_user_one_time_password_send"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="one_time_password_send",),
        migrations.AddField(
            model_name="user",
            name="otp_expire",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
