# Generated by Django 4.2.7 on 2023-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_user_one_time_password_send_user_otp_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_expire",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
