# Generated by Django 4.2.7 on 2023-11-10 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_user_otp_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_expire",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
