# Generated by Django 4.2.7 on 2023-11-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_user_otp_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="otp_created_at",
            new_name="one_time_password_created_at",
        ),
        migrations.RemoveField(model_name="user", name="otp_expire",),
    ]
