# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0020_rename_otp_created_at_user_one_time_password_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="one_time_password_created_at",),
        migrations.RemoveField(model_name="user", name="one_time_password_sent_email",),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(default="0000", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
