# Generated by Django 4.2.7 on 2023-11-11 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_onetimepassword_sent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimepassword",
            options={
                "verbose_name": "One Time Password",
                "verbose_name_plural": "One Time Passwords",
            },
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 11, 13, 28, 20, 210493, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
