# Generated by Django 4.2.7 on 2023-11-11 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_onetimepassword_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="onetimepassword", name="expires_at",),
        migrations.RemoveField(model_name="onetimepassword", name="is_sent",),
        migrations.AlterField(
            model_name="onetimepassword",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
