# Generated by Django 4.2.7 on 2023-11-11 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_onetimepassword_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 11, 15, 19, 13, 465013, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
