# Generated by Django 4.2.7 on 2023-11-12 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="one_time_password",),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 12, 15, 8, 17, 208875, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
