# Generated by Django 4.2.7 on 2023-11-12 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_user_one_time_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 12, 15, 11, 51, 572596, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
