# Generated by Django 4.2.7 on 2023-11-12 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 12, 21, 36, 51, 557783, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
