# Generated by Django 4.2.7 on 2024-01-17 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 17, 11, 43, 39, 627516, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
