# Generated by Django 4.2.7 on 2023-11-13 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 13, 9, 57, 39, 890841, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
