# Generated by Django 4.2.7 on 2023-11-14 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 14, 23, 38, 31, 760458, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
