# Generated by Django 4.2.7 on 2023-11-15 09:07

import datetime
import django.contrib.auth.tokens
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "expires_in",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 11, 15, 9, 8, 48, 39490, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            bases=(
                models.Model,
                django.contrib.auth.tokens.PasswordResetTokenGenerator,
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 9, 12, 48, 41915, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
