# Generated by Django 4.2.7 on 2023-11-15 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_verificationtoken_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationtoken",
            options={
                "verbose_name": "Verification Token",
                "verbose_name_plural": "Verification Tokens",
            },
        ),
        migrations.AddField(
            model_name="verificationtoken",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 9, 18, 33, 358056, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="verificationtoken",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 9, 14, 33, 355420, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
