# Generated by Django 4.2.7 on 2023-11-15 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_alter_verificationtoken_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 11, 3, 34, 190420, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="verificationtoken",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 10, 59, 34, 186661, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
