# Generated by Django 4.2.7 on 2023-11-15 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_onetimepassword_expires_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 13, 3, 17, 719089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
