# Generated by Django 4.2.7 on 2023-11-15 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 13, 58, 23, 495594, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
