# Generated by Django 4.2.7 on 2023-11-15 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 14, 19, 49, 873348, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
