# Generated by Django 4.2.7 on 2023-11-15 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 19, 42, 10, 156159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
