# Generated by Django 4.2.7 on 2023-11-22 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_profile_company_name_profile_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 22, 22, 1, 34, 92193, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
