# Generated by Django 4.2.7 on 2023-11-22 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_alter_onetimepassword_expires_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 22, 22, 35, 48, 697735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
