# Generated by Django 4.2.7 on 2023-11-28 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0078_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 20, 9, 38, 925863, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
