# Generated by Django 4.2.7 on 2023-11-28 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0080_companyprofile_privateprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 20, 24, 7, 16791, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
