# Generated by Django 4.2.7 on 2023-11-28 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0086_rename_companyprofile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 20, 43, 44, 152872, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
