# Generated by Django 4.2.7 on 2023-11-29 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0089_rename_is_company_user_is_business_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Company", new_name="Business",),
        migrations.RenameModel(old_name="Private", new_name="Individual",),
        migrations.AlterModelOptions(
            name="business",
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="individual",
            options={
                "verbose_name": "Individual Profile",
                "verbose_name_plural": "Individual Profiles",
            },
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 13, 4, 36, 541939, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
