# Generated by Django 4.2.7 on 2023-12-12 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0091_alter_business_user_alter_individual_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 12, 13, 13, 17, 364366, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
