# Generated by Django 4.2.7 on 2023-12-12 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0093_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_business",),
        migrations.RemoveField(model_name="user", name="is_individual",),
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("Individual", "Individual"), ("Business", "Business")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 12, 16, 47, 43, 760324, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
