# Generated by Django 4.2.7 on 2023-12-13 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0094_remove_user_is_business_remove_user_is_individual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 13, 23, 28, 26, 886636, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
