# Generated by Django 4.2.7 on 2023-12-15 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0099_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 15, 18, 0, 46, 317362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
