# Generated by Django 4.2.7 on 2023-12-20 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0107_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 20, 17, 17, 12, 621784, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
