# Generated by Django 4.2.7 on 2024-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
