# Generated by Django 4.2.7 on 2024-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contactmail_date_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
