# Generated by Django 4.2.7 on 2024-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_newsletter_subscribed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="subscribed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
