from django.urls import path
from . import views

urlpatterns = [
    path(
        route="api/v1/properties",
        view=views.PropertyAPIView.as_view(),
        name="api-v1-properties",
    ),
    path(
        route="api/v1/properties/<int:pk>",
        view=views.PropertyDetailAPIView.as_view(),
        name="api-v1-properties-property-details",
    ),
    path(
        route="api/v1/properties/create-property",
        view=views.PropertyCreateAPIView.as_view(),
        name="api-v1-properties-create-property",
    ),
    path(
        route="api/v1/properties/update-property/<int:pk>",
        view=views.PropertyUpdateAPIView.as_view(),
        name="api-v1-properties-update-property",
    ),
    path(
        route="api/v1/properties/delete-property/<int:pk>",
        view=views.PropertyDeleteAPIView.as_view(),
        name="api-v1-properties-delete-property",
    ),
    path(
        route="api/v1/tour-schedules",
        view=views.TourSchedulesAPIView.as_view(),
        name="api-v1-tour-schedules",
    ),
    path(
        route="api/v1/tour-schedules/<int:pk>",
        view=views.TourScheduleDetailAPIView.as_view(),
        name="api-v1-tour-schedules-details",
    ),
    path(
        route="api/v1/tour-schedules/create-tour-schedule",
        view=views.TourScheduleCreateAPIView.as_view(),
        name="api-v1-tour-schedules-create-tour-schedule",
    ),
    path(
        route="api/v1/tour-schedules/update-tour-schedule/<int:pk>",
        view=views.TourScheduleUpdateAPIView.as_view(),
        name="api-v1-tour-schedules-update-tour-schedule",
    ),
    path(
        route="api/v1/tour-schedules/delete-tour-schedule/<int:pk>",
        view=views.TourScheduleDeleteAPIView.as_view(),
        name="api-v1-tour-schedules-delete-tour-schedule",
    ),
    path(
        route="api/v1/reviews",
        view=views.ReviewsAPIView.as_view(),
        name="api-v1-reviews",
    ),
    path(
        route="api/v1/reviews/<int:pk>",
        view=views.ReviewDetailAPIView.as_view(),
        name="api-v1-review-details",
    ),
    path(
        route="api/v1/reviews/create-review",
        view=views.ReviewCreateAPIView.as_view(),
        name="api-v1-reviews-create-review",
    ),
    path(
        route="api/v1/reviews/update-review/<int:pk>",
        view=views.ReviewUpdateAPIView.as_view(),
        name="api-v1-reviews-update-review",
    ),
    path(
        route="api/v1/reviews/delete-review/<int:pk>",
        view=views.ReviewDeleteAPIView.as_view(),
        name="api-v1-reviews-delete-review",
    ),
]
