from django.urls import path
from . import views

urlpatterns = [
    path(
        route="api/v1/listing-statuses",
        view=views.ListingStatusAPIView.as_view(),
        name="api-v1-listing-statuses",
    ),
    path(
        route="api/v1/listing-statuses/<int:pk>",
        view=views.ListingStatusDetailAPIView.as_view(),
        name="api-v1-listing-statuses-details",
    ),
    path(
        route="api/v1/listing-statuses/create-listing-status",
        view=views.ListingStatusCreateAPIView.as_view(),
        name="api-v1-listing-statuses-create-listing-status",
    ),
    path(
        route="api/v1/listing-statuses/update-listing-status/<int:pk>",
        view=views.ListingStatusUpdateAPIView.as_view(),
        name="api-v1-listing-statuses-update-listing-status",
    ),
    path(
        route="api/v1/listing-statuses/delete-listing-status/<int:pk>",
        view=views.ListingStatusDeleteAPIView.as_view(),
        name="api-v1-listing-statuses-delete-listing-status",
    ),
    path(
        route="api/v1/categories",
        view=views.CategoryAPIView.as_view(),
        name="api-v1-categories",
    ),
    path(
        route="api/v1/categories/<int:pk>",
        view=views.CategoryDetailAPIView.as_view(),
        name="api-v1-category-details",
    ),
    path(
        route="api/v1/categories/create-category",
        view=views.CategoryCreateAPIView.as_view(),
        name="api-v1-categories-create-category",
    ),
    path(
        route="api/v1/categories/update-category/<int:pk>",
        view=views.CategoryUpdateAPIView.as_view(),
        name="api-v1-categories-update-category",
    ),
    path(
        route="api/v1/categories/delete-category/<int:pk>",
        view=views.CategoryDeleteAPIView.as_view(),
        name="api-v1-categories-delete-category",
    ),
    path(
        route="api/v1/properties",
        view=views.PropertyAPIView.as_view(),
        name="api-v1-properties",
    ),
    path(
        route="api/v1/properties/<int:pk>",
        view=views.PropertyDetailAPIView.as_view(),
        name="api-v1-properties-property-details",
    ),
    path(
        route="api/v1/properties/create-property",
        view=views.PropertyCreateAPIView.as_view(),
        name="api-v1-properties-create-property",
    ),
    path(
        route="api/v1/properties/update-property/<int:pk>",
        view=views.PropertyUpdateAPIView.as_view(),
        name="api-v1-properties-update-property",
    ),
    path(
        route="api/v1/properties/delete-property/<int:pk>",
        view=views.PropertyDeleteAPIView.as_view(),
        name="api-v1-properties-delete-property",
    ),
    path(
        route="api/v1/tour-schedules",
        view=views.TourSchedulesAPIView.as_view(),
        name="api-v1-tour-schedules",
    ),
    path(
        route="api/v1/tour-schedules/<int:pk>",
        view=views.TourScheduleDetailAPIView.as_view(),
        name="api-v1-tour-schedules-details",
    ),
    path(
        route="api/v1/tour-schedules/create-tour-schedule",
        view=views.TourScheduleCreateAPIView.as_view(),
        name="api-v1-tour-schedules-create-tour-schedule",
    ),
    path(
        route="api/v1/tour-schedules/update-tour-schedule/<int:pk>",
        view=views.TourScheduleUpdateAPIView.as_view(),
        name="api-v1-tour-schedules-update-tour-schedule",
    ),
    path(
        route="api/v1/tour-schedules/delete-tour-schedule/<int:pk>",
        view=views.TourScheduleDeleteAPIView.as_view(),
        name="api-v1-tour-schedules-delete-tour-schedule",
    ),
    path(
        route="api/v1/reviews",
        view=views.ReviewsAPIView.as_view(),
        name="api-v1-reviews",
    ),
    path(
        route="api/v1/reviews/<int:pk>",
        view=views.ReviewDetailAPIView.as_view(),
        name="api-v1-review-details",
    ),
    path(
        route="api/v1/reviews/create-review",
        view=views.ReviewCreateAPIView.as_view(),
        name="api-v1-reviews-create-review",
    ),
    path(
        route="api/v1/reviews/update-review/<int:pk>",
        view=views.ReviewUpdateAPIView.as_view(),
        name="api-v1-reviews-update-review",
    ),
    path(
        route="api/v1/reviews/delete-review/<int:pk>",
        view=views.ReviewDeleteAPIView.as_view(),
        name="api-v1-reviews-delete-review",
    ),
]
