# Generated by Django 4.2.7 on 2024-01-01 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 1, 23, 56, 1, 933145, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
