# Generated by Django 4.2.7 on 2024-01-02 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="uuid", field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 0, 21, 40, 660255, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
