# Generated by Django 4.2.7 on 2024-01-03 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 3, 14, 24, 37, 57857, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
