# Generated by Django 4.2.7 on 2024-01-08 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_business_id_alter_individual_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 8, 17, 28, 14, 503537, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
