# Generated by Django 4.2.7 on 2024-01-09 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 22, 25, 30, 549696, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
