# Generated by Django 4.2.7 on 2024-01-22 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 22, 11, 45, 39, 549759, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
