# Generated by Django 4.2.7 on 2024-01-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_alter_onetimepassword_expires_in"),
    ]

    operations = [
        migrations.RemoveField(model_name="onetimepassword", name="expires_in",),
    ]
