# Generated by Django 4.2.7 on 2024-03-19 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimepassword",
            name="expires_in",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 19, 11, 19, 39, 346353, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
    ]
