# Generated by Django 4.2.7 on 2024-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
