# Generated by Django 4.2.7 on 2024-01-18 11:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Amenity", "verbose_name_plural": "Amenities",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(max_length=100, null=True)),
            ],
            options={"verbose_name": "City", "verbose_name_plural": "Cities",},
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.FloatField()),
            ],
            options={"verbose_name": "Education", "verbose_name_plural": "Educations",},
        ),
        migrations.CreateModel(
            name="HealthAndMedical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.FloatField()),
            ],
            options={
                "verbose_name": "Health & Medical",
                "verbose_name_plural": "Health & Medicals",
            },
        ),
        migrations.CreateModel(
            name="ListingStatus",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Listing Status",
                "verbose_name_plural": "Listing Statuses",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        upload_to="property_images/plans/<django.db.models.fields.CharField>"
                    ),
                ),
                ("floor_square_meters", models.FloatField()),
                ("number_of_bedrooms", models.IntegerField()),
                ("number_of_bathrooms", models.IntegerField()),
            ],
            options={"verbose_name": "Plan", "verbose_name_plural": "Plans",},
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "main_image",
                    models.ImageField(null=True, upload_to="property_images"),
                ),
                (
                    "image_files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="property_images/<django.db.models.fields.CharField>",
                    ),
                ),
                ("year_of_built", models.IntegerField()),
                ("number_of_bedrooms", models.IntegerField()),
                ("number_of_bathrooms", models.IntegerField()),
                ("square_meters", models.FloatField()),
                ("parking_space", models.IntegerField()),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=5, null=True)),
                ("latitude", models.FloatField(max_length=20, null=True)),
                ("longitude", models.FloatField(max_length=20, null=True)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        max_length=10000, unique=True
                    ),
                ),
                ("video", models.FileField(upload_to="property_videos")),
                ("is_featured", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=300, null=True, unique=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        related_name="amenities", to="properties.amenities"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="properties.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="properties.city",
                    ),
                ),
                (
                    "education",
                    models.ManyToManyField(blank=True, to="properties.education"),
                ),
                (
                    "favourites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_and_medical",
                    models.ManyToManyField(
                        blank=True, to="properties.healthandmedical"
                    ),
                ),
                (
                    "listing_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_statuses",
                        to="properties.listingstatus",
                    ),
                ),
                (
                    "plan",
                    models.ManyToManyField(
                        blank=True, related_name="property_plan", to="properties.plan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["date_posted"],
            },
        ),
        migrations.CreateModel(
            name="Shopping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.FloatField()),
            ],
            options={"verbose_name": "Shopping",},
        ),
        migrations.CreateModel(
            name="Transportation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.FloatField()),
            ],
            options={
                "verbose_name": "Transportation",
                "verbose_name_plural": "Transportations",
            },
        ),
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("date_sent", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("message", models.TextField(max_length=10000)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Schedule",
                "verbose_name_plural": "Tour Schedules",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("date_posted", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=100, null=True)),
                ("rate", models.IntegerField()),
                ("content", models.TextField(max_length=20000)),
                ("active", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews",},
        ),
        migrations.AddField(
            model_name="property",
            name="shopping",
            field=models.ManyToManyField(blank=True, to="properties.shopping"),
        ),
        migrations.AddField(
            model_name="property",
            name="transportation",
            field=models.ManyToManyField(blank=True, to="properties.transportation"),
        ),
        migrations.AddField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OfferContact",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("date_sent", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=100, null=True)),
                ("message", models.TextField(max_length=20000, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Contact",
                "verbose_name_plural": "Offer Contacts",
            },
        ),
    ]
