# Generated by Django 4.2.7 on 2024-02-21 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0006_property_purchasing_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="purchasing_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="quantity_of_purchases",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
