# Generated by Django 4.2.7 on 2024-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_remove_property_image_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="property_images"),
        ),
    ]
