# Generated by Django 4.2.7 on 2024-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_property_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="property", name="images",),
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.ManyToManyField(to="properties.image"),
        ),
    ]
