# Generated by Django 4.2.7 on 2024-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_image_remove_property_images_property_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="images",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.ImageField(null=True, upload_to="property_images"),
        ),
    ]
