# Generated by Django 4.2.7 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_remove_property_images_delete_image_property_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenities",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="amenity_image"),
        ),
    ]
