# Generated by Django 4.2.7 on 2024-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_rename_email_tourschedule_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="plan",),
        migrations.AlterField(
            model_name="review",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="OfferContact",),
        migrations.DeleteModel(name="Plan",),
    ]
