# Generated by Django 4.2.7 on 2024-03-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_alter_tourschedule_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tourschedule",
            old_name="to",
            new_name="customer",
        ),
    ]
