# Generated by Django 4.2.7 on 2024-03-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_images"),
    ]

    operations = [
        migrations.DeleteModel(name="Images",),
    ]
