# Generated by Django 4.2.7 on 2024-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_alter_property_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_details_images"
                    ),
                ),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images",},
        ),
        migrations.RemoveField(model_name="property", name="images",),
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="property_images", to="properties.img"
            ),
        ),
    ]
