# Generated by Django 4.2.7 on 2024-03-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0028_remove_property_purchasing_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="purchasing_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="education",
            field=models.ManyToManyField(
                blank=True, related_name="education", to="properties.education"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="health_and_medical",
            field=models.ManyToManyField(
                blank=True,
                related_name="health_and_medical",
                to="properties.healthandmedical",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="properties.img"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="shopping",
            field=models.ManyToManyField(
                blank=True, related_name="shopping", to="properties.shopping"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="transportation",
            field=models.ManyToManyField(
                blank=True,
                related_name="transportation",
                to="properties.transportation",
            ),
        ),
    ]
