# Generated by Django 4.2.7 on 2024-03-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0029_property_purchasing_user_alter_property_education_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourschedule",
            name="phone_number",
            field=models.CharField(max_length=100),
        ),
    ]
