# Generated by Django 4.2.7 on 2024-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0032_alter_img_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_cities_images"
            ),
        ),
    ]
