# Generated by Django 4.2.7 on 2024-04-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0033_alter_city_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_city_image.jpg",
                null=True,
                upload_to="property_cities_images",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthandmedical",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="properties.city",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shopping",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transportation",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
