# Generated by Django 4.2.7 on 2024-01-01 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Amenity", "verbose_name_plural": "Amenities",},
        ),
        migrations.CreateModel(
            name="ListingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Listing Status",
                "verbose_name_plural": "Listing Statuses",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Property Type",
                "verbose_name_plural": "Property Types",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="property_images")),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="property_videos")),
                ("featured", models.BooleanField(default=False)),
                ("price", models.IntegerField()),
                ("number_of_bedrooms", models.IntegerField()),
                ("number_of_bathrooms", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("favourite", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("square_meters", models.FloatField()),
                ("year_of_built", models.IntegerField()),
                ("parking_space", models.IntegerField()),
                (
                    "amenities",
                    models.ManyToManyField(
                        related_name="amenities", to="properties.amenities"
                    ),
                ),
                (
                    "listing_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_status",
                        to="properties.listingstatus",
                    ),
                ),
                (
                    "property_type",
                    models.ManyToManyField(
                        related_name="property_type", to="properties.propertytype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["date_posted"],
            },
        ),
    ]
