# Generated by Django 4.2.7 on 2024-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.FloatField(default=1, null=True),
        ),
    ]
