# Generated by Django 4.2.7 on 2024-01-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="listing_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_statuses",
                to="properties.listingstatus",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.ManyToManyField(
                related_name="property_types", to="properties.propertytype"
            ),
        ),
    ]
