# Generated by Django 4.2.7 on 2024-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="property_categories_images"),
        ),
    ]
