# Generated by Django 4.2.7 on 2024-01-01 23:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_property_listing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                max_length=10000, unique=True
            ),
        ),
    ]
