# Generated by Django 4.2.7 on 2024-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenities",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="listingstatus",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="propertytype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
