# Generated by Django 4.2.7 on 2024-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_amenities_id_alter_listingstatus_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="image",),
        migrations.AddField(
            model_name="property",
            name="image_files",
            field=models.FileField(null=True, upload_to="property_images"),
        ),
    ]
