# Generated by Django 4.2.7 on 2024-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_remove_property_image_property_image_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nearby",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.ImageField(upload_to="property_images/icons")),
            ],
        ),
        migrations.CreateModel(
            name="OfferContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        upload_to="property_images/plans/<django.db.models.fields.CharField>"
                    ),
                ),
                ("floor_square_meters", models.FloatField()),
                ("number_of_bedrooms", models.IntegerField()),
                ("number_of_bathrooms", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="country_code",
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="main_image",
            field=models.ImageField(null=True, upload_to="property_images"),
        ),
        migrations.AlterField(
            model_name="property",
            name="image_files",
            field=models.FileField(
                upload_to="property_images/<django.db.models.fields.CharField>"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
