# Generated by Django 4.2.7 on 2024-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_nearby_offercontact_plan_reviews_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image_files",
            field=models.FileField(
                null=True,
                upload_to="property_images/<django.db.models.fields.CharField>",
            ),
        ),
    ]
