# Generated by Django 4.2.7 on 2024-01-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_image_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property", old_name="favourite", new_name="is_favourite",
        ),
        migrations.RenameField(
            model_name="property", old_name="featured", new_name="is_featured",
        ),
    ]
