# Generated by Django 4.2.7 on 2024-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_rename_favourite_property_is_favourite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="image_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="property_images/<django.db.models.fields.CharField>",
            ),
        ),
    ]
