# Generated by Django 4.2.7 on 2024-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_property_postal_code_alter_property_image_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearby",
            name="icon",
            field=models.ImageField(upload_to="icons/properties"),
        ),
        migrations.AlterField(
            model_name="property", name="price", field=models.CharField(max_length=20),
        ),
    ]
