# Generated by Django 4.2.7 on 2024-01-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0011_alter_nearby_icon_alter_property_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100, null=True)),
                ("rate", models.IntegerField()),
                ("content", models.TextField(max_length=20000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews",},
        ),
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("message", models.TextField(max_length=10000)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Schedule",
                "verbose_name_plural": "Tour Schedules",
            },
        ),
        migrations.DeleteModel(name="Reviews",),
        migrations.DeleteModel(name="Schedule",),
        migrations.AlterModelOptions(
            name="nearby",
            options={"verbose_name": "Nearby", "verbose_name_plural": "Nearby"},
        ),
        migrations.AlterModelOptions(
            name="offercontact",
            options={
                "verbose_name": "Offer Contact",
                "verbose_name_plural": "Offer Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"verbose_name": "Plan", "verbose_name_plural": "Plans"},
        ),
        migrations.AddField(
            model_name="offercontact",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="offercontact",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="offercontact",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="offercontact",
            name="message",
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name="offercontact",
            name="phone_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby",
                to="properties.nearby",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="offer_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_contact",
                to="properties.offercontact",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="properties.plan",
            ),
        ),
        migrations.AlterField(
            model_name="offercontact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="country_code",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="properties.review",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tour_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_schedule",
                to="properties.tourschedule",
            ),
        ),
    ]
