# Generated by Django 4.2.7 on 2024-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0012_review_tourschedule_delete_reviews_delete_schedule_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="plan",),
        migrations.AddField(
            model_name="property",
            name="plan",
            field=models.ManyToManyField(
                null=True, related_name="property_plan", to="properties.plan"
            ),
        ),
    ]
