# Generated by Django 4.2.7 on 2024-01-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_alter_property_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearbyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("distance", models.FloatField(max_length=8)),
                ("rate", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="nearby",
            name="category",
            field=models.ManyToManyField(to="properties.nearbycategory"),
        ),
    ]
