# Generated by Django 4.2.7 on 2024-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_remove_property_plan_alter_review_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourschedule",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
