# Generated by Django 4.2.7 on 2024-01-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_nearbycategory_nearby_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nearbycategory",
            options={
                "verbose_name": "Nearby Category",
                "verbose_name_plural": "Nearby Categories",
            },
        ),
        migrations.AlterField(
            model_name="nearbycategory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
