# Generated by Django 4.2.7 on 2024-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_alter_nearbycategory_options_alter_nearbycategory_id"),
    ]

    operations = [
        migrations.RenameModel(old_name="NearbyCategory", new_name="NearbyObject",),
        migrations.AlterModelOptions(
            name="nearbyobject",
            options={
                "verbose_name": "Nearby Object",
                "verbose_name_plural": "Nearby Objects",
            },
        ),
        migrations.RemoveField(model_name="nearby", name="category",),
        migrations.AddField(
            model_name="nearby",
            name="nearby_objects",
            field=models.ManyToManyField(
                related_name="nearby_objects", to="properties.nearbyobject"
            ),
        ),
    ]
