# Generated by Django 4.2.7 on 2024-01-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0017_rename_nearbycategory_nearbyobject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourschedule",
            name="date_sent",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
