# Generated by Django 4.2.7 on 2024-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_tourschedule_date_sent"),
    ]

    operations = [
        migrations.RemoveField(model_name="tourschedule", name="time",),
        migrations.AlterField(
            model_name="tourschedule", name="date", field=models.DateTimeField(),
        ),
    ]
