# Generated by Django 4.2.7 on 2024-03-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0018_alter_tourschedule_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourschedule",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tour_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
