# Generated by Django 4.2.7 on 2024-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_remove_tourschedule_time_alter_tourschedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="offercontact",
            name="date_sent",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
