# Generated by Django 4.2.7 on 2024-01-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_remove_property_review_review_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="date_sent", new_name="date_posted",
        ),
        migrations.RemoveField(model_name="property", name="offer_contact",),
        migrations.RemoveField(model_name="property", name="tour_schedule",),
        migrations.AddField(
            model_name="offercontact",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="tourschedule",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.property",
            ),
        ),
    ]
