# Generated by Django 4.2.7 on 2024-01-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0022_rename_date_sent_review_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourschedule",
            name="property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.property",
            ),
        ),
    ]
