# Generated by Django 4.2.7 on 2024-01-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "properties",
            "0024_remove_property_is_favourite_property_favourites_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="nearby", old_name="name", new_name="category",
        ),
        migrations.AlterField(
            model_name="property",
            name="favourites",
            field=models.ManyToManyField(
                related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="nearby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby",
                to="properties.nearby",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="plan",
            field=models.ManyToManyField(
                blank=True, related_name="property_plan", to="properties.plan"
            ),
        ),
    ]
