# Generated by Django 4.2.7 on 2024-01-08 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0025_rename_name_nearby_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
