# Generated by Django 4.2.7 on 2024-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_delete_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="property_images"),
        ),
    ]
