# Generated by Django 4.2.7 on 2024-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_alter_property_favourites"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.IntegerField()),
            ],
            options={"verbose_name": "Education", "verbose_name_plural": "Educations",},
        ),
        migrations.CreateModel(
            name="HealthAndMedical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.IntegerField()),
            ],
            options={
                "verbose_name": "Health & Medical",
                "verbose_name_plural": "Health & Medicals",
            },
        ),
        migrations.CreateModel(
            name="Transportation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.IntegerField()),
            ],
            options={
                "verbose_name": "Transportation",
                "verbose_name_plural": "Transportations",
            },
        ),
        migrations.RemoveField(model_name="property", name="nearby",),
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(name="Nearby",),
        migrations.DeleteModel(name="NearbyObject",),
        migrations.AddField(
            model_name="property",
            name="education",
            field=models.ManyToManyField(blank=True, to="properties.education"),
        ),
        migrations.AddField(
            model_name="property",
            name="health_and_medical",
            field=models.ManyToManyField(blank=True, to="properties.healthandmedical"),
        ),
        migrations.AddField(
            model_name="property",
            name="transportation",
            field=models.ManyToManyField(blank=True, to="properties.transportation"),
        ),
    ]
