# Generated by Django 4.2.7 on 2024-01-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_education_healthandmedical_transportation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education", name="rate", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="healthandmedical", name="rate", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="transportation", name="rate", field=models.FloatField(),
        ),
    ]
