# Generated by Django 4.2.7 on 2024-03-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_img_remove_property_images_property_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="purchasing_user",),
        migrations.RemoveField(model_name="property", name="quantity_of_purchases",),
    ]
