# Generated by Django 4.2.7 on 2024-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0028_alter_education_rate_alter_healthandmedical_rate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Shopping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("distance", models.FloatField()),
                ("rate", models.FloatField()),
            ],
            options={"verbose_name": "Shopping",},
        ),
        migrations.AddField(
            model_name="property",
            name="shopping",
            field=models.ManyToManyField(blank=True, to="properties.shopping"),
        ),
    ]
