# Generated by Django 4.2.7 on 2024-01-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0029_shopping_property_shopping"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="city",),
    ]
