# Generated by Django 4.2.7 on 2024-03-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0030_alter_tourschedule_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="property_details_images"
            ),
        ),
    ]
