# Generated by Django 4.2.7 on 2024-01-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0031_city_property_city"),
    ]

    operations = [
        migrations.RenameModel(old_name="PropertyType", new_name="Category",),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.RemoveField(model_name="property", name="property_type",),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="properties.category",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="properties.city",
            ),
        ),
    ]
