# Generated by Django 4.2.6 on 2023-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0002_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
