# Generated by Django 4.2.7 on 2023-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("Business", "Business"),
                    ("Real Estate", "Real Estate"),
                    ("Popular", "Popular"),
                    ("Luxury Villa", "Luxury Villa"),
                    ("Design", "Design"),
                ],
                max_length=50,
            ),
        ),
    ]
