# Generated by Django 4.2.7 on 2023-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_tag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
