# Generated by Django 4.2.7 on 2023-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="categories", new_name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
