# Generated by Django 4.2.7 on 2023-11-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_categories_article_category_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="category",),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
            ),
        ),
    ]
