# Generated by Django 4.2.7 on 2024-01-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_date_posted_alter_article_id_and_more"),
        ("blog", "0005_alter_article_date_posted_alter_article_id_and_more"),
    ]

    operations = []
