# Generated by Django 4.2.7 on 2023-11-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_article_category_article_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category", new_name="name",
        ),
    ]
