# Generated by Django 4.2.7 on 2024-01-22 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_merge_20240111_2102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
