# Generated by Django 4.2.7 on 2024-03-22 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
