# Generated by Django 4.2.7 on 2024-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_comment_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
