# Generated by Django 4.2.7 on 2023-11-14 18:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(max_length=10000, unique=True),
        ),
    ]
