# Generated by Django 4.2.7 on 2023-11-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_article_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["date_posted"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
