# Generated by Django 4.2.7 on 2023-11-15 13:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_2",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                max_length=10000, null=True, unique=True
            ),
        ),
    ]
