# Generated by Django 4.2.7 on 2023-11-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_article_content_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="content_2",),
    ]
