# Generated by Django 4.2.7 on 2023-11-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_remove_article_category_article_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="category",),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(related_name="article", to="blog.category"),
        ),
    ]
