# Generated by Django 4.2.7 on 2023-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_comment_active_comment_dislikes_comment_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag", name="tag", field=models.CharField(max_length=50),
        ),
    ]
