# Generated by Django 4.2.7 on 2023-12-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_tag_tag"),
    ]

    operations = [
        migrations.RenameField(model_name="tag", old_name="tag", new_name="name",),
    ]
