# Generated by Django 4.2.7 on 2023-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_rename_tag_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tag", name="name", field=models.CharField(max_length=100),
        ),
    ]
