# Generated by Django 4.2.7 on 2023-12-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_tag_slug_alter_category_slug_alter_tag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="content", new_name="comment",
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_parent",
                to="blog.comment",
            ),
        ),
    ]
