# Generated by Django 4.2.7 on 2023-12-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_rename_content_comment_comment_alter_comment_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="email",),
    ]
