# Generated by Django 4.2.7 on 2023-12-20 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0034_commentfeedback_remove_commentlike_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="dislikes",),
        migrations.RemoveField(model_name="comment", name="likes",),
        migrations.DeleteModel(name="CommentFeedback",),
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="comment_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                related_name="comment_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
