# Generated by Django 4.2.7 on 2023-12-29 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("content", models.TextField(max_length=2000)),
            ],
            options={
                "verbose_name_plural": "Contact Mails",
                "ordering": ["-date_sent"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email", models.EmailField(max_length=200, null=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Newsletters",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
