# Generated by Django 4.2.7 on 2024-03-27 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contactmail_date_sent_alter_contactmail_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="date_sent",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="subscribed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
