# Generated by Django 4.2.7 on 2023-11-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_newsletter_options_newsletter_subscribed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200, null=True, unique=True)),
            ],
            options={"verbose_name_plural": "Emails",},
        ),
    ]
