# Generated by Django 4.2.7 on 2023-11-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailsender"),
    ]

    operations = [
        migrations.DeleteModel(name="EmailSender",),
    ]
