# Generated by Django 4.2.7 on 2023-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_emailsender"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
