# Generated by Django 4.2.7 on 2023-11-22 21:56

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_newsletter_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", phone_field.models.PhoneField(max_length=31)),
                ("email", models.CharField(max_length=150)),
                ("message", models.TextField(max_length=2000)),
            ],
            options={
                "verbose_name_plural": "Contact Form Mails",
                "ordering": ["-date_sent"],
            },
        ),
    ]
