# Generated by Django 4.2.7 on 2023-11-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_contactmail"),
    ]

    operations = [
        migrations.RemoveField(model_name="newsletter", name="is_verified",),
    ]
