# Generated by Django 4.2.7 on 2023-11-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_newsletter_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="phone_number",
            field=models.CharField(max_length=150),
        ),
    ]
