# Generated by Django 4.2.7 on 2023-11-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_contactmail_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmail",
            options={
                "ordering": ["-date_sent"],
                "verbose_name_plural": "Contact Mails",
            },
        ),
        migrations.RenameField(
            model_name="contactmail", old_name="message", new_name="content",
        ),
    ]
